// <auto-generated />
using System;
using BankingApp.DataAccessLayer.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingApp.DataAccessLayer.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20210713190648_ChangedWrongTableNames")]
    partial class ChangedWrongTableNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankingApp.Entities.Entities.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalculationFormula")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalulationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositeSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthsCount")
                        .HasColumnType("int");

                    b.Property<float>("Percents")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("BankingApp.Entities.Entities.MonthlyPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepositId")
                        .HasColumnType("int");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<float>("Percents")
                        .HasColumnType("real");

                    b.Property<decimal>("TotalMonthSum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepositId");

                    b.ToTable("MonthlyPayments");
                });

            modelBuilder.Entity("BankingApp.Entities.Entities.MonthlyPayment", b =>
                {
                    b.HasOne("BankingApp.Entities.Entities.Deposit", "Deposit")
                        .WithMany("MonthlyPayments")
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("BankingApp.Entities.Entities.Deposit", b =>
                {
                    b.Navigation("MonthlyPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
